### ISSUE TITLE
Compatibility with phpStorm 2017.1

### ISSUE THREAD

**Issue by tammiju** [david0/idea-prado-plugin#2]
Hi,
Something wrong with new version of PhpStorm and Prado-plugin.
PhpStorm 2017.1
Build #PS-171.3780.104, built on March 21, 2017
JRE: 1.8.0_112-release-736-b13 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.10.5

Everything worked fine with the previous version (2016.3).

This error will appear immediately after the opening PhpStorm (Prado-plugin installed).
```
com.jetbrains.php.lang.psi.elements.Variable.getInferredType(I)Lcom/jetbrains/php/lang/psi/resolve/types/PhpType;
java.lang.NoSuchMethodError: com.jetbrains.php.lang.psi.elements.Variable.getInferredType(I)Lcom/jetbrains/php/lang/psi/resolve/types/PhpType;
	at idea.plugins.prado.PradoControlUtil.classForFieldReference(PradoControlUtil.java:22)
	at idea.plugins.prado.completion.ControlTypeProvider.getType(ControlTypeProvider.java:39)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:49)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:39)
	at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:56)
...

java.lang.NoSuchMethodError: com.jetbrains.php.lang.psi.elements.Variable.getInferredType(I)Lcom/jetbrains/php/lang/psi/resolve/types/PhpType;
	at idea.plugins.prado.PradoControlUtil.classForFieldReference(PradoControlUtil.java:22)
	at idea.plugins.prado.completion.ControlTypeProvider.getType(ControlTypeProvider.java:39)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:49)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:39)
	at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:56)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:39)
...
```

**Comment by zendre4** [comment]
Same error on 2017.1.3

**Comment by Ruslan-F** [comment]
Same error on Win 10. Any chance for update?..

**Comment by david0** [comment]
Hi, at the moment i'm not working with Prado so I don't have the drive from myself, sorry. But feel free to fix it and open a PR
